### ISSUE TITLE
cannot import name reshape_book

### ISSUE THREAD

**Issue by saeedesmaili** [al1b/Calibre-KiPEO#10]
I'm using Calibre 3.40.1 and I had the KiPEO plugin already and it was fine. But today I found out that it's not accessible in the plugins section, so I tried to add it again and when loading the plugin in the preferences, Calibre displays the following error:

> **ImportError**: cannot import name reshape_book
calibre 3.40.1  embedded-python: True is64bit: True
Linux-4.18.0-16-generic-x86_64-with-debian-buster-sid Linux ('64bit', 'ELF')
('Linux', '4.18.0-16-generic', '#17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019')
Python 2.7.15
Linux: ('debian', 'buster/sid', '')
Interface language: None
Successfully initialized third party plugins: Goodreads (1, 4, 0) && Wikidata (1, 3, 0)
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 472, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 61, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 200, in load
  File "site-packages/calibre/customize/zipplugin.py", line 184, in load_module
  File "calibre_plugins.dummy1.__init__", line 5, in <module>
ImportError: cannot import name reshape_book

![image](https://user-images.githubusercontent.com/13351748/56090969-22abea80-5ebe-11e9-9cfb-82d3ed43a55f.png)

**Comment by ahmdyasser** [comment]
you found any solutions?

**Comment by saeedesmaili** [comment]
@ahmdyasser not yet.

**Comment by saeedesmaili** [comment]
@ahmdyasser check this one:
https://github.com/al1b/Calibre-KiPEO/issues/13#issuecomment-612573299
