### ISSUE TITLE
problem in version 3.48.0 instalation: ImportError: cannot import name reshape_book

### ISSUE THREAD

**Issue by m-jalal** [al1b/Calibre-KiPEO#13]
calibre, version 3.48.0
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name reshape_book

calibre 3.48 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.15+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: DeDRM (6, 6, 3)
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 319, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 201, in load
  File "site-packages\polyglot\builtins.py", line 186, in reload
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.dummy1.__init__", line 5, in <module>
ImportError: cannot import name reshape_book

**Comment by syedsimanta03** [comment]
same here

**Comment by al1b** [comment]
I don't have access to the al1b/Calibre-KiPEO repo now, in another forked
repo I fixed the problem.

https://github.com/0x414c49/Calibre-KiPEO

You can get fixed released version here:
https://github.com/0x414c49/Calibre-KiPEO/releases
