### ISSUE TITLE
Plugin Menu Doesn't Appear

### ISSUE THREAD

**Issue by khoerodin** [al1b/Calibre-KiPEO#18]
I downloaded from https://github.com/0x414c49/Calibre-KiPEO/releases/tag/0.0.2 but the plugins menu doesn't appear
![Screenshot (5)](https://user-images.githubusercontent.com/2797396/109004909-efeaf400-76db-11eb-94b7-cf76dfe3136c.png)

Calibre version 4.23
@al1b @Monirzadeh

**Comment by Monirzadeh** [comment]
i try to install plugin with calibre 5.11 get bellow error
do you get any error on calibre 4.23 while install plugin?
```
calibre 5.11  embedded-python: True is64bit: True
Linux-5.3.18-lp152.63-default-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.3.18-lp152.63-default', '#1 -------- (98caa86)')
Python 3.8.5
Interface language: None
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 316, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 293, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.dummy1.__init__", line 5, in <module>
    import reshaper
ModuleNotFoundError: No module named 'reshaper'
```

**Comment by khoerodin** [comment]
No error with calibre 4.23 @Monirzadeh

**Comment by 0x414c49** [comment]
I'm installing Calibre 5.11.0 to check the plugin. Since I don't have a Kindle anymore I forgot to keep this plugin updated.

**Comment by Monirzadeh** [comment]
> No error with calibre 4.23 @Monirzadeh

please extract plugin and run to get more information
```
calibre-debug --add-simple-plugin=__init__.py
```
> I'm installing Calibre 5.11.0 to check the plugin. Since I don't have a Kindle anymore I forgot to keep this plugin updated.

:)
@Khoerodin for now i use [koreader]( https://github.com/koreader/koreader) project that it so much easear to read RTL on kindle and any other device
