### ISSUE TITLE
issue while installing plugin on calibre 3.38.1

### ISSUE THREAD

**Issue by amirslear** [al1b/Calibre-KiPEO#9]
I got this error while installing amazing keipi :(
calibre, version 3.38.1
ERROR: Unhandled exception: <b>ImportError</b>:cannot import name reshape_book

calibre 3.38.1  embedded-python: True is64bit: False
Windows-10-10.0.10586-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.10586')
Python 2.7.15+
Windows: ('10', '10.0.10586', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 200, in load
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.dummy1.__init__", line 5, in <module>
ImportError: cannot import name reshape_book

**Comment by al1b** [comment]
I will check it as soon as possible.

**Comment by GlassesPi** [comment]
I have same problem in second try of KiPEO installation with new release of calibre v 3.38.1 :(
First one was about something like css stuff IDK

**Comment by GlassesPi** [comment]
I reinstalled to show you the first error
![image](https://user-images.githubusercontent.com/30589130/51469468-a609e400-1d86-11e9-8098-7a17aa79d3d8.png)

and there is log:
calibre, version 3.38.1
ERROR: Unhandled exception: <b>ImportError</b>:No module named cssutils.css

calibre 3.38.1 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.17763-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.17763')
Python 2.7.15+
Windows: ('10', '10.0.17763', 'SP0', u'Multiprocessor Free')
Interface language: None
Traceback (most recent call last):
  File "site-packages\calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 472, in add_plugin
  File "site-packages\calibre\customize\ui.py", line 61, in load_plugin
  File "site-packages\calibre\customize\zipplugin.py", line 202, in load
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.dummy1.__init__", line 5, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 184, in load_module
  File "calibre_plugins.dummy1.reshaper", line 3, in <module>
ImportError: No module named cssutils.css

**Comment by al1b** [comment]
Ok, I'm working on the problem.

**Comment by al1b** [comment]
Due this change of Calibre we are facing this issue:
https://github.com/kovidgoyal/calibre/commit/dd7d8ea3c4f47e315623d882d6b68339da959ab9

**Comment by mshahmalaki** [comment]
> Due this change of Calibre we are facing this issue:
> [kovidgoyal/calibre@dd7d8ea](https://github.com/kovidgoyal/calibre/commit/dd7d8ea3c4f47e315623d882d6b68339da959ab9)

So we just replace 'cssutils.css' with 'css_parser.css'.

**Comment by al1b** [comment]
Hi,

I know this and I did, the latest release has another issue.
